version: "3.9"
services:
  postgres:
    image: postgres
    container_name: my-postgres
    networks:
      - compose-bridge
  app:
    image: alegomes/app:1.0
    container_name: my-app
    networks:
      - compose-bridge
    ports: 
      - 8080:9000
    depends_on:
      - postgres

networks:
  compose-bridge:
    driver: bridge